<?xml version="1.0"?>

<package format="3">

  <name>erc_bringup</name>

  <version>1.0.0</version>

  <description>
    ERC 2026 full system bringup package.
  </description>

  <maintainer email="ghala@example.com">
    Ghala
  </maintainer>

  <license>Apache-2.0</license>

  <buildtool_depend>
    ament_python
  </buildtool_depend>

  <exec_depend>
    launch
  </exec_depend>

  <exec_depend>
    launch_ros
  </exec_depend>

  <exec_depend>
    erc_perception
  </exec_depend>

  <exec_depend>
    erc_navigation
  </exec_depend>

  <exec_depend>
    erc_manipulation
  </exec_depend>

  <exec_depend>
    erc_mission
  </exec_depend>

  <export>
    <build_type>
      ament_python
    </build_type>
  </export>

</package>
