<?xml version="1.0"?>

<package format="3">

  <name>erc_manipulation</name>

  <version>1.0.0</version>

  <description>
    ERC 2026 manipulation interface package.
  </description>

  <maintainer email="ghala@example.com">
    Ghala
  </maintainer>

  <license>Apache-2.0</license>

  <buildtool_depend>
    ament_python
  </buildtool_depend>

  <depend>
    rclpy
  </depend>

  <depend>
    std_msgs
  </depend>

  <export>
    <build_type>
      ament_python
    </build_type>
  </export>

</package>
